
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres

development:
  <<: *default
  database: ieat_rails_development

test:
  <<: *default
  database: ieat_rails_test

production:
  <<: *default
  database: ieat_rails_production
  username: ieat_rails
  password: <%= ENV['IEAT_RAILS_DATABASE_PASSWORD'] %>
